### ISSUE TITLE
generate advisor sets

### ISSUE THREAD

**Issue by azyro** [Kingsford-Group/scallopadvising#2] opened 2019-05-09 12:04 UTC
Hi danfdeblasio,
Now I want to use scallop for reference-based transcript assembly, if I want to obtain  optimize parameter. The first step is to use scallop_coordinate_ascent.pl to find an optimal parameter choice? In addition，in your paper ,you say this procedure can be parallelized. 
My code is `./scallop_coordinate_ascent.pl ./temp_scallop_coordinate_ascent ./S1.bam`
how should I do it in paralle? 
Thanks in advance for your help and for the great tool!
Napo

**Comment by danfdeblasio** [comment] 2019-05-09 16:01
Hi Napo, 

For normal use cases, you won't need to create your own advisor sets, the ones I created are quite general. For that you would just checkout the repo and run: 
`/ScallopAdvising.pl --working_dir temp/ --input_bam in.bam --output_gtf out.gtf --reference ref.gtf scallop_configs/*.config`.

If you really want to learn new sets, the command you have should do fine. 

None of the scripts as implemented are parallelized. 

While all of the parts of the *advising* step are embarrassingly parallel, that's not something I have addressed in the release code yet. Its something I would like to do. The coordinate ascent is *not* parallelizable as presented in the preprint. 

Please don't hesitate to ask if that didn't answer your question or you have any others. 

Dan

**Comment by azyro** [comment] 2019-05-10 01:02
Thank you very much ,Dan
I have another question that I need your help，I am using  scallop for reference-based transcript assembly of plant. If this case，your advisor sets still can be used in my data? if it not be used, Will use my own data to obtain optimize parameter? When I use your scallop_coordinate_ascent.pl script, I encounter `sh: line 1: 286084 Aborted                 (core dumped)` ,which step can cause this problem?

**Comment by danfdeblasio** [comment] 2019-05-10 19:49
I have not tested how well the human-trained parameters work for plants, but I would be interesting to see what you find if you use them. 

For the training, that seems to be an issue with one of the calls that the script is making to an external program. I rely on several standard linux programs as well as `scallop` and `gffcompare` to be in the `$PATH`. Also, you will need to swap out the reference to GRCH38, which is hard coded in the script. Since its an external call and just an Abort, its hard to know for sure where the problem is. Had it printed anything to the screen before this happened? If not its likely due to the initial run of `scallop` and `gffcompare`, if a single number had been output then its something with the incremental stepping.

**Comment by azyro** [comment] 2019-05-15 14:53
Thank you,Dan
So far ,I have obtained many auc file corresponding to different  parameter.From have obtained result, we found the `min_router_count` parameter,change result apparent。But I can't find the meaning of the parameter .Can you tell me the meaning of the parameter?

**Comment by danfdeblasio** [comment] 2019-05-15 15:00
Unfortunately, I am not well versed on the actual function of each
parameter inside `scallop`. You may be able to find it in the documentation
of [Scallop](http://github.com/Kingsford-Group/scallop) or in the
supplement of their paper.

Sorry.

**Comment by azyro** [comment] 2019-05-16 00:26
Thank you so much,Dan
I have checked the documentation and the supplement of their paper. No related information,I have send email to the scallop developer.Thanks again for your kind help.

**Closed as completed** 2019-06-06 19:40 UTC
